# Generated by Django 3.2.6 on 2021-09-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgpro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedb',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
